# src/main/resources/db.properties
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/hospital_db
db.user=postgres
db.password=1234

# ??????????? ??? DaoFactory, ???? ????????????? ??'? ?????
# dao.factory.class=com.example.hospital.model.dao.jdbc.JdbcDaoFactory